# Site settings
title: The Accidental Developer
header-img: img/home-bg.png
email: karen.ag.flores@gmail.com
copyright_name: kagflores
description: > # this means to ignore newlines until "baseurl:"
  The journey of a geologist becoming a developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kagflores
learn_profile: kagflores
email_username: karen.ag.flores@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
